BaseCapabilities:
  - capability_code: ALL
    capability: SuperUser Permissions
    min_level: 5
  - capability_code: DIRECTORY
    capability: Use the District Directory
    min_level: 1
  - capability_code: HISTORY
    capability: View User Changes
    min_level: 1
  - capability_code: OWN_USER
    capability: Edit Own User
    min_level: 0
  - capability_code: LOGIN
    capability: Login
    min_level: 0
  - capability_code: NON_PUBLIC_GROUP
    capability: View Hidden Scout Group Details
    min_level: 3
AllModels:
  Users:
    baseLevel: 1
    viewRestricted: false
    fieldLock: 2
  ScoutGroups:
    baseLevel: 3
    viewRestricted: false
    fieldLock: false
  Sections:
    baseLevel: 2
    viewRestricted: false
    fieldLock: false
  RoleTypes:
    baseLevel: 4
    viewRestricted: false
    fieldLock: false
  Documents:
    baseLevel: 4
    viewRestricted: false
    fieldLock: false
  Notifications:
    baseLevel: 2
    viewRestricted: false
    fieldLock: false
AllCapabilities:
  - LOGIN
  - OWN_USER
UnauthorizedExceptions:
  - Authorization\Exception\ForbiddenException
  - Authorization\Exception\MissingIdentityException
