apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: application
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: application
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/frontend: "true"
        io.kompose.service: application
    spec:
      containers:
        - image: application
          name: application
          ports:
            - containerPort: 8765
            - containerPort: 80
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: .
              name: application-data
      restartPolicy: Always
      volumes:
        - name: application-data
          persistentVolumeClaim:
            claimName: application-data
status: {}
