apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: application
  name: application
spec:
  ports:
    - name: "5100"
      port: 5100
      targetPort: 8765
    - name: "5101"
      port: 5101
      targetPort: 80
    - name: "5102"
      port: 5102
      targetPort: 8000
  selector:
    io.kompose.service: application
status:
  loadBalancer: {}
