apiVersion: v1
data:
  POSTGRES_PASSWORD: 1e57a452a094728c291bc42bf2bc7eb8d9fd8844d1369da2bf728588b46c4e75
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: database-config-credentials-docker-env
  name: config-credentials-docker-env
