ConfigKeys:
  - Queue
  - Security
  - CloudConvert
  - Datasources
  - DefaultAdmin
  - SparkPost
  - Session
  - GoogleClient
  - IdeHelper
  - DatabaseLog
  - Log
  - Email
  - EmailTransport
  - Error
  - Cache
  - App

SecureKeys:
  - Security
  - CloudConvert
  - Datasources
  - SparkPost
  - Cache

IncludedAppConfigKeys:
  - debug

ExcludedAppConfigKeys:
  - Filesystem

ApplicationConfigKeys:
  - BaseCapabilities
  - EntityCapabilities
  - FieldCapabilities
  - ActionOverrides
  - AllModels
  - AllCapabilities
  - UnauthorizedExceptions
  - DailyCrons
  - RoleTemplates
  - FileTypes
  - FunctionalAreas
  - IconStandards
  - SearchConfigured
  - NotificationTypes
  - Passwordable
  - Webservices
