name: GitHub CI

env:
    APP_DL_INSTALL_MODE: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  phpUnit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']
        async: ['Y', 'N']

    name: PHP ( ${{ matrix.php-version }} ) Async ( ${{ matrix.async }} ) DB ( Postgres )

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: leaders
          POSTGRES_PASSWORD: cake
          POSTGRES_USER: app
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, apcu, pdo_pgsql, redis, xdebug
          ini-values: xdebug.mode="develop,coverage", apc.enable_cli=1
          coverage: xdebug

      - name: Set Async Setup
        run: if [[ ${{ matrix.async }} == 'N' ]]; then rm phpunit.xml.dist; fi

      - name: Set Async Setup
        run: if [[ ${{ matrix.async }} == 'N' ]]; then mv phpunit-ci.xml.dist phpunit.xml.dist; fi

      - name: Update composer
        run: composer self-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-scripts

      - name: Create Config Files
        run: composer console-install

      - name: Run tests
        run: |
          if [[ ${{ matrix.async }} == 'Y' ]]; then
            composer test-with-coverage
          else
            composer test
          fi

      - name: List Files
        run: ls -al

      - name: CodeCov Upload Coverage
        if: ${{ matrix.async == 'Y' }}
        run: bash <(curl -s https://codecov.io/bash)

      - name: Code Climate Coverage Action
        if: ${{ matrix.async == 'Y' }}
        continue-on-error: true
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 414f50dc9563e45b17137a9e716cb56eeda2c179633b3d3db567f1849a584f2f
          coverageLocations: |
            ${{github.workspace}}/clover.xml:clover

  staticCheck:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        check-type: [ 'coding-standards', 'validate' ]

    name: Static Check ( ${{ matrix.check-type }} )

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: leaders
          POSTGRES_PASSWORD: cake
          POSTGRES_USER: app
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, apcu

      - name: Update composer
        run: composer self-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --optimize-autoloader

      - name: Add Config Files
        run: composer console-install

      - name: Run Static Fix
        if: ${{ matrix.check-type == 'coding-standards' }}
        run: composer cs-fix

      - name: Run Static Check
        run: composer ${{ matrix.check-type }}
