name: GitHub CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.3', '7.4']
        db-type: [pgsql]

    name: PHP ${{ matrix.php-version }} & ${{ matrix.db-type }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: leaders
          POSTGRES_PASSWORD: cake
          POSTGRES_USER: app
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, apcu, pdo_${{ matrix.db-type }}, redis
          ini-values: apc.enable_cli = 1

      - name: Set Extended Test Timeout
        run: export COMPOSER_PROCESS_TIMEOUT=900

      - name: Set App File Config
        run: mv config/app_file.travis.php config/app_file.php

      - name: Set App Config
        run: mv config/app.github-ci.php config/app.php

      - name: Set General YML Config
        run: mv config/Environment/travis_parameters.yml config/Environment/app_parameters.yml

      - name: Update composer
        run: composer self-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install --no-scripts --no-suggest

      - name: Run tests
        run: composer test

  coding-standard:
    name: Coding Standard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, apcu

      - name: Set App File Config
        run: mv config/app_file.travis.php config/app_file.php

      - name: Set App Config
        run: mv config/app.github-ci.php config/app.php

      - name: Set General YML Config
        run: mv config/Environment/travis_parameters.yml config/Environment/app_parameters.yml

      - name: Update composer
        run: composer self-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: PHP CodeSniffer
        run: composer cs-check
