name: GitHub CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4']
        db-type: [pgsql]
        composer-type: [lowest, stable, dev, install]

    name: PHP ${{ matrix.php-version }} & ${{ matrix.db-type }} & ${{ matrix.composer-type }}

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: leaders
          POSTGRES_PASSWORD: cake
          POSTGRES_USER: app

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, apcu, pdo_${{ matrix.db-type }}
          ini-values: apc.enable_cli = 1

      - name: Set Extended Test Timeout
        run: export COMPOSER_PROCESS_TIMEOUT=900

      - name: Set App File Config
        run: mv config/app_file.travis.php config/app_file.php

      - name: Set App Config
        run: mv config/app.travis.php config/app.php

      - name: Set General YML Config
        run: mv config/Environment/travis_parameters.yml config/Environment/app_parameters.yml

      - name: Update composer
        run: composer self-update

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: |
          if [[ ${{ matrix.composer-type }} == 'lowest' ]]; then
            composer update --prefer-dist --no-progress --no-suggest --prefer-stable --prefer-lowest
          elif [[ ${{ matrix.composer-type }} == 'stable' ]]; then
            composer update --prefer-dist --no-progress --no-suggest --prefer-stable
          elif [[ ${{ matrix.composer-type }} == 'dev' ]]; then
            composer update --prefer-dist --no-progress --no-suggest
          else
            composer install --no-scripts
          fi

      - name: Run tests
        run: composer test
